spring:
 batch:
  job:
   enabled: false
  jdbc:
   initialize-schema: ALWAYS
 datasource:
  driver-class-name: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521:orcl
  username: siva
  password: velpula